import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
// Tailwind 4 ships a first-party Vite plugin. It replaces the PostCSS pipeline
// entirely — postcss.config.js is gone, and autoprefixer with it, since v4
// handles vendor prefixing itself via Lightning CSS.
import tailwindcss from '@tailwindcss/vite'
import { VitePWA } from 'vite-plugin-pwa'

// https://vite.dev/config/
export default defineConfig({
  plugins: [
    react(),
    tailwindcss(),
    VitePWA({
      // manifest.webmanifest is generated by scripts/gen-brand.ts from
      // brand.config.json (see index.html's <link rel="manifest">) —
      // this plugin only handles the service worker.
      manifest: false,
      injectManifest: { injectionPoint: 'self.__WB_MANIFEST' },
      strategies: 'injectManifest',
      srcDir: 'src',
      filename: 'sw.ts',
      registerType: 'prompt',
      injectRegister: false,
      // Off by default. A dev service worker takes control of the page via
      // registerSW({ immediate: true }) in lib/pwa.ts, and once it is in the
      // request path every lazy route import fails with
      // `TypeError: Failed to fetch dynamically imported module` — which
      // RouteError reads as isOffline and renders as the 503 maintenance page.
      // First load is a blank screen, every navigation after is 503, and
      // nothing is logged as an error. The registration is stored per origin,
      // so it survives server restarts and outlives whatever build created it.
      //
      // Still needed to test PWA behaviour — subscribeToPush awaits
      // navigator.serviceWorker.ready, which never resolves without a worker.
      // Turn it on deliberately for that: `$env:VITE_DEV_SW=1; npm run dev`.
      // Shell variable only — vite does not load .env into the config's own
      // process.env, so putting it in .env will not work.
      //
      // If it has already been registered on an origin, this flag will not
      // remove it: DevTools -> Application -> Clear site data, then reload.
      devOptions: { enabled: !!process.env.VITE_DEV_SW, type: 'module' },
    }),
  ],
})
