import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { VitePWA } from 'vite-plugin-pwa'

// https://vite.dev/config/
export default defineConfig({
  plugins: [
    react(),
    VitePWA({
      // manifest.webmanifest is generated by scripts/gen-brand.ts from
      // brand.config.json (see index.html's <link rel="manifest">) —
      // this plugin only handles the service worker.
      manifest: false,
      injectManifest: { injectionPoint: 'self.__WB_MANIFEST' },
      strategies: 'injectManifest',
      srcDir: 'src',
      filename: 'sw.ts',
      registerType: 'autoUpdate',
      injectRegister: false,
      devOptions: { enabled: true, type: 'module' },
    }),
  ],
})
